services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=rmlmanager'
      - 'POSTGRES_PASSWORD=rmlmanager'
      - 'POSTGRES_USER=rmlmanager'
    ports:
      - '5432:5432'
